---
- name: 'Debug de variáveis de ambiente (CORRIGIDO)'
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Mostra as variáveis injetadas pelo AWX
      shell: |
        echo "========================================="
        echo "===       VARIAVEIS DO NETBOX       ==="
        echo "========================================="
        env | grep NETBOX || echo ">>> Nenhuma variável NETBOX encontrada."
        echo ""
        echo "NETBOX_API (URL do Host): [{{ lookup('env', 'NETBOX_API') }}]"
        echo "NETBOX_TOKEN presente: [{{ 'Sim' if lookup('env', 'NETBOX_TOKEN') else 'Não' }}]"
        echo ""
        echo "========================================="
        echo "===        VARIAVEIS DO AWX         ==="
        echo "========================================="
        env | grep AWX || echo ">>> Nenhuma variável AWX encontrada."
        echo ""
        echo "AWX_USERNAME: [{{ lookup('env', 'AWX_USERNAME') }}]"
        echo "AWX_PASSWORD presente: [{{ 'Sim' if lookup('env', 'AWX_PASSWORD') else 'Não' }}]"
        echo ""
        echo "========================================="