---
- name: Executar sincronização AWX → NetBox via script Python
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Executar script Python diretamente do repositório
      ansible.builtin.command: >
        python3 scripts/awx-netbox.py
      args:
        chdir: "{{ ansible_env.ANSIBLE_PROJECT_DIR | default('.') }}"
      environment:
        AWX_USERNAME: "{{ AWX_USERNAME }}"
        AWX_PASSWORD: "{{ AWX_PASSWORD }}"
        NETBOX_API: "{{ NETBOX_API }}"
        NETBOX_TOKEN: "{{ NETBOX_TOKEN }}"
