---
- name: Executar sincronizacao AWX para NetBox
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Debug variaveis
      shell: |
        echo "=== VARIAVEIS NETBOX ==="
        env | grep NETBOX || echo "Nenhuma encontrada"
        echo ""
        echo "=== VARIAVEIS AWX ==="
        env | grep AWX || echo "Nenhuma encontrada"
        echo ""
        echo "=== DEBUG URL ==="
        echo "NETBOX_API: [$NETBOX_API]"
        echo "NETBOX_URL: [$NETBOX_URL]"
        echo "Tamanho NETBOX_API: ${#NETBOX_API}"
        echo "Tamanho NETBOX_URL: ${#NETBOX_URL}"
      register: debug_result

    - name: Mostrar debug
      debug:
        var: debug_result.stdout_lines

    - name: Executar script Python
      shell: |
        cd /runner/project
        python3 -u scripts/awx-netbox.py
      register: script_result
      failed_when: false

    - name: Mostrar resultado
      debug:
        msg: |
          Return code: {{ script_result.rc }}
          STDOUT: {{ script_result.stdout }}
          STDERR: {{ script_result.stderr }}