---
- name: Executar sincronização AWX → NetBox via script Python
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Executar script Python diretamente do repositório
      ansible.builtin.shell: |
        echo "🔍 Verificando variáveis..."
        echo "AWX_USERNAME: ${AWX_USERNAME:-'NÃO DEFINIDO'}"
        echo "AWX_PASSWORD: ${AWX_PASSWORD:+'DEFINIDO'}"
        echo "NETBOX_API: ${NETBOX_API:-'NÃO DEFINIDO'}"
        echo "NETBOX_TOKEN: ${NETBOX_TOKEN:+'DEFINIDO'}"
        echo ""
        echo "🚀 Executando script Python..."
        python3 scripts/awx-netbox.py
      args:
        chdir: "{{ ansible_env.ANSIBLE_PROJECT_DIR | default('.') }}"
      register: script_result

    - name: Mostrar resultado do script
      debug:
        var: script_result
