---
- name: Executar sincronizacao AWX para NetBox
  hosts: localhost
  gather_facts: false

  tasks:
    - name: Debug variaveis
      shell: |
        echo "AWX_USERNAME: $AWX_USERNAME"
        echo "AWX_PASSWORD: ${AWX_PASSWORD:+DEFINIDO}"
        echo "NETBOX_API: $NETBOX_API"
        echo "NETBOX_TOKEN: ${NETBOX_TOKEN:+DEFINIDO}"
        echo "Diretorio atual: $(pwd)"
        ls -la
      register: debug_result

    - name: Mostrar debug
      debug:
        var: debug_result.stdout_lines

    - name: Executar script Python
      shell: |
        cd /runner/project
        python3 -u scripts/awx-netbox.py
      register: script_result
      failed_when: false

    - name: Mostrar resultado
      debug:
        msg: |
          Return code: {{ script_result.rc }}
          STDOUT: {{ script_result.stdout }}
          STDERR: {{ script_result.stderr }}